# Generated by Django 5.0.6 on 2024-06-22 18:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(5000000)])),
                ('term', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(60)])),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('monthly_payment', models.CharField(max_length=255)),
                ('total_payment', models.CharField(max_length=255)),
                ('total_interest', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('message', models.TextField(max_length=5000, verbose_name='Сообщение')),
                ('check_status', models.BooleanField(choices=[(False, 'Не проверено'), (True, 'Проверено')], default=0, verbose_name='Статус проверки')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=255)),
                ('term', models.CharField(max_length=255)),
                ('interest_rate', models.CharField(max_length=255)),
                ('monthly_payment', models.CharField(max_length=255)),
                ('total_payment', models.CharField(max_length=255)),
                ('total_interest', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=255, verbose_name='Отчество')),
                ('date_birth', models.DateField(verbose_name='Дата рождения')),
                ('passport_series', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)], verbose_name='Серия паспорта')),
                ('passport_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)], verbose_name='Номер паспорта')),
                ('registration_address', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[А-ЯЁа-яё\\s,.-]+$')], verbose_name='Адрес регистрации')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Адрес электронной почты')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.loan', verbose_name='Расчеты калькулятора')),
            ],
        ),
    ]
